name: portflow

volumes:
  portflow-postgres-data:
  portflow-mongodb-data:

services:
  postgresql:
    container_name: portflow-pg
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: portflow
      POSTGRES_PASSWORD: portflow
      POSTGRES_DB: portflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portflow -d portflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - portflow-postgres-data:/var/lib/postgresql/data

  mongodb:
     container_name: portflow-mongo
     image: mongo:8
     environment:
         MONGO_INITDB_ROOT_USERNAME: portflow
         MONGO_INITDB_ROOT_PASSWORD: portflow
         MONGO_INITDB_DATABASE: terminal_service
     ports:
        - "27017:27017"  
     healthcheck:
        test: ["CMD", "mongosh", "--username","portflow", "--password", "portflow"]
        interval: 5s
        timeout: 5s
        retries: 10     
     volumes:
        - ./mongo/init:/docker-entrypoint-initdb.d
        - portflow-mongodb-data:/data/db

  terminal-service:
        image: terminal-service:latest
        container_name: terminal-service
        build:
          context: ../terminal-service
          dockerfile: docker/Dockerfile
        ports:  
           - "8082:8082"  

  container-service:
        image: container-service:latest
        container_name: container-service
        build:
          context: ../container-service
          dockerfile: docker/Dockerfile
        ports:
           - "8081:8081"

  eureka-server:
        image: eureka-server:latest
        container_name: eureka
        build:
          context: ../eureka
          dockerfile: docker/Dockerfile
        ports:
           - "8761:8761"    

  api-gateway:
        image: api-gateway:latest
        container_name: api-gateway
        build:
          context: ../api-gateway
          dockerfile: docker/Dockerfile
        ports:
           - "9999:9999"      
