spring:
  application:
    name: container-service

  datasource:
    url: jdbc:postgresql://postgresql:5432/portflow?currentSchema=container_service
    username: portflow
    password: portflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "[default_schema]": container_service
        "[format_sql]": true
      show-sql: true

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

api:
  endpoints:
    terminal: TERMINAL-SERVICE

resilience4j:
  circuitbreaker:
    instances:
      terminalValidation:
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      terminalValidation:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
